### ISSUE TITLE
FSUnit.xUnit Property tests are not being discovered/executed, 

### ISSUE THREAD

**Issue by parthopdas** [parthopdas/tddstud10#25]
Even though xunit and nunit theory tests work fine.

**Comment by parthopdas** [comment]
Also update the sample under AcceptanceTest uncommenting the PropertyTest in there.

**Comment by ashwinsathyar** [comment]
Investigated this. There is nothing wrong in the system. The issue is with the FsCheck.xUnit infrastructure. When the test case is discovered the discoverer is not returning the right code file path and the line number. This hinders the experience in Visual Studio itelsef.
Filed the following issue to track this.

https://github.com/fscheck/FsCheck/issues/297

**Comment by parthopdas** [comment]
This is working and there is a ContractTest for this as well. [See here](https://github.com/parthopdas/tddstud10-testprojects/blob/master/e2e/FSXUnit2xNUnit2x.NET45/Library1.fs#L12)
